@extends('layouts.admin')

@section('title', 'Financial Report: ' . $report->report_name)

@section('content')
<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header d-flex justify-content-between align-items-center">
                    <h3 class="card-title">📊 {{ $report->report_name }}</h3>
                    <div>
                        <button onclick="window.print()" class="btn btn-info">
                            <i class="fas fa-print"></i> Print
                        </button>
                        <a href="{{ route('finance.reports.index') }}" class="btn btn-secondary">
                            <i class="fas fa-arrow-left"></i> Back to Reports
                        </a>
                    </div>
                </div>

                <div class="card-body">
                    <div class="row mb-3">
                        <div class="col-md-6">
                            <strong>Report Type:</strong> {{ ucwords(str_replace('_', ' ', $report->report_type)) }}
                        </div>
                        <div class="col-md-6">
                            <strong>Report Date:</strong> {{ $report->report_date->format('M d, Y') }}
                        </div>
                    </div>

                    <div class="row mb-3">
                        <div class="col-md-6">
                            <strong>Generated By:</strong> {{ $report->creator->name ?? 'System' }}
                        </div>
                        <div class="col-md-6">
                            <strong>Generated On:</strong> {{ $report->created_at->format('M d, Y H:i') }}
                        </div>
                    </div>

                    <hr>

                    @if($report->report_type === 'balance_sheet')
                        @include('finance.reports.partials.balance-sheet', ['data' => $report->report_data])
                    @elseif($report->report_type === 'income_statement')
                        @include('finance.reports.partials.income-statement', ['data' => $report->report_data])
                    @elseif($report->report_type === 'cash_flow')
                        @include('finance.reports.partials.cash-flow', ['data' => $report->report_data])
                    @elseif($report->report_type === 'trial_balance')
                        @include('finance.reports.partials.trial-balance', ['data' => $report->report_data])
                    @elseif($report->report_type === 'budget_variance')
                        @include('finance.reports.partials.budget-variance', ['data' => $report->report_data])
                    @else
                        <div class="alert alert-info">
                            <h6>Raw Report Data</h6>
                            <pre>{{ json_encode($report->report_data, JSON_PRETTY_PRINT) }}</pre>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>

<style>
@media print {
    .btn, .card-header .btn-group {
        display: none !important;
    }
}
</style>
@endsection
